set(_CATKIN_CURRENT_PACKAGE "objectDetection")
set(objectDetection_VERSION "0.0.0")
set(objectDetection_MAINTAINER "connect <connect@todo.todo>")
set(objectDetection_PACKAGE_FORMAT "2")
set(objectDetection_BUILD_DEPENDS "rospy" "std_msgs")
set(objectDetection_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(objectDetection_BUILDTOOL_DEPENDS "catkin")
set(objectDetection_BUILDTOOL_EXPORT_DEPENDS )
set(objectDetection_EXEC_DEPENDS "rospy" "std_msgs")
set(objectDetection_RUN_DEPENDS "rospy" "std_msgs")
set(objectDetection_TEST_DEPENDS )
set(objectDetection_DOC_DEPENDS )
set(objectDetection_URL_WEBSITE "")
set(objectDetection_URL_BUGTRACKER "")
set(objectDetection_URL_REPOSITORY "")
set(objectDetection_DEPRECATED "")