set(_CATKIN_CURRENT_PACKAGE "apriltag")
set(apriltag_VERSION "0.0.0")
set(apriltag_MAINTAINER "connect <connect@todo.todo>")
set(apriltag_PACKAGE_FORMAT "2")
set(apriltag_BUILD_DEPENDS "rospy" "std_msgs")
set(apriltag_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(apriltag_BUILDTOOL_DEPENDS "catkin")
set(apriltag_BUILDTOOL_EXPORT_DEPENDS )
set(apriltag_EXEC_DEPENDS "rospy" "std_msgs")
set(apriltag_RUN_DEPENDS "rospy" "std_msgs")
set(apriltag_TEST_DEPENDS )
set(apriltag_DOC_DEPENDS )
set(apriltag_URL_WEBSITE "")
set(apriltag_URL_BUGTRACKER "")
set(apriltag_URL_REPOSITORY "")
set(apriltag_DEPRECATED "")