set(_CATKIN_CURRENT_PACKAGE "tagTracking")
set(tagTracking_VERSION "0.0.0")
set(tagTracking_MAINTAINER "connect <connect@todo.todo>")
set(tagTracking_PACKAGE_FORMAT "2")
set(tagTracking_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(tagTracking_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(tagTracking_BUILDTOOL_DEPENDS "catkin")
set(tagTracking_BUILDTOOL_EXPORT_DEPENDS )
set(tagTracking_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(tagTracking_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(tagTracking_TEST_DEPENDS )
set(tagTracking_DOC_DEPENDS )
set(tagTracking_URL_WEBSITE "")
set(tagTracking_URL_BUGTRACKER "")
set(tagTracking_URL_REPOSITORY "")
set(tagTracking_DEPRECATED "")